M48
; DRILL file KiCad 10.0.5 date 2026-09-27T21:39:05
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-27T21:39:05+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T2
X5.0Y-5.0
X5.0Y-95.0
X95.0Y-5.0
X95.0Y-95.0
T1
X12.8Y-24.1G85X12.8Y-27.1
G05
X82.7Y-24.1G85X82.7Y-27.1
G05
M30
